# Generated by Django 3.0 on 2019-12-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('car_desc', models.TextField()),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('car_year', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
